title: Rogerio Alves
email: racardoso@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal page.
baseurl: ""
url: ""
# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

